version: "3.7"
services:
    biroda-dev:
        build: .
        env_file:
            - docker.env
        container_name: biroda-dev
        ports:
            - "3000"
        volumes:
            - "./persistent:/srv/persistent"
            - "./app:/srv/app"
            - "./node:/srv/node"
            - "./docker-resources/.p10k.zsh:/root/.p10k.zsh"
            - "./docker-resources/.zshrc:/root/.zshrc"
        stdin_open: true
        tty: true